### ISSUE TITLE
Ques: REACT VARS

### ISSUE THREAD

**Issue by daddydrac** [testdrivenio/testdriven-kubernetes-app#19]
What examples would go in these vars:

```
 - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
 - REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL}
 - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
 - REACT_APP_SCORES_SERVICE_URL=${REACT_APP_SCORES_SERVICE_URL}
```

**Comment by mjhea0** [comment]
On AWS, the public IP of your Application Load Balancer.

**Comment by daddydrac** [comment]
Am I able to leave this blank to run locally?
`${REACT_APP_USERS_SERVICE_URL}`

**Comment by mjhea0** [comment]
No, set it to the URL and port of the exposed service from Docker Compose. 

Something like:

```
export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1:5001
export REACT_APP_EXERCISES_SERVICE_URL=http://127.0.0.1:5002
export REACT_APP_SCORES_SERVICE_URL=http://127.0.0.1:5003
```

**Comment by joehoeller** [comment]
Cool, thank you. I did add Sentry on-prem to the docker-compose file, and ity causes the other URLs (during REST calls fron GUI) to 404. Is there a reason for that, or something I am missing?

**Comment by joehoeller** [comment]
For example, my ports match whatever is in dockerfile, as you stated above:
```
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=http://127.0.0.1:5001
      - REACT_APP_API_GATEWAY_URL=http://127.0.0.1:3007
      - REACT_APP_EXERCISES_SERVICE_URL=http://127.0.0.1:5002
      - REACT_APP_SCORES_SERVICE_URL=http://127.0.0.1:5003
```
